// Code generated by schema tool; DO NOT EDIT.

import * as wasmlib from '../../../lib/wasmlib';
import * as wasmtypes from '../../../lib/wasmlib/wasmtypes';

export class RussfestEvents {

    test(): void {
        const enc = wasmlib.eventEncoder('russfest.test');
        wasmlib.eventEmit(enc);
    }
}
